In [14]:
import numpy as np
import math
import csv
from proj1_helpers import *
from Hadrien import *
from ML_methods import *
from features_engineering import *
import matplotlib.pyplot as plt


%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [15]:
y, tx, ids = load_csv_data("data_csv/train.csv", sub_sample=True)

In [16]:
print("y has shape {0}".format(y.shape))
print("X has shape {0}".format(tx.shape))

y has shape (5000,)
X has shape (5000, 30)


In [17]:
## TODO : remove NAN before standardization, or at least not consider them in np.mean() and np.std.
tx_nan = transform_to_nan(tx, -900)
tx_nan_norm, mean_x, std_x = standardize_with_nan(tx_nan)

In [18]:
tx_0_norm = transform_nan_to_zero(tx_nan_norm)
features_log = [0, 2, 3, 5, 9, 13, 16, 23, 29]
features_sin_cos = [15, 18, 20, 25, 28]

tx_0_norm_adujsted_log = transform_feature_log(tx_0_norm, features_log)
tx_0_norm_adujsted_log_sin = transform_feature_sin(tx_0_norm_adujsted_log, features_sin_cos)
tx_0_norm_adujsted_log_sin_cos = transform_feature_cos(tx_0_norm_adujsted_log_sin, features_sin_cos)

txx = tx_0_norm_adujsted_log_sin_cos

In [19]:

def split_data(x, y, ratio, myseed=1):
    """split the dataset based on the split ratio."""
    # set seed
    np.random.seed(myseed)
    # generate random indices
    num_row = len(y)
    indices = np.random.permutation(num_row)
    index_split = int(np.floor(ratio * num_row))
    index_tr = indices[: index_split]
    index_te = indices[index_split:]
    # create split
    x_tr = x[index_tr]
    x_te = x[index_te]
    y_tr = y[index_tr]
    y_te = y[index_te]
    return x_tr, x_te, y_tr, y_te

In [20]:
x_tr,x_te,y_tr,y_te=split_data(txx,y,0.8)

In [21]:
initial_w_gd = np.zeros(txx.shape[1])
max_iters = 10
gamma = 0.25
gd_losses, gd_ws = gradient_descent(y_tr, x_tr, initial_w_gd, max_iters, gamma)

Gradient Descent(0/9): loss=1.0, w0=-0.0410642217740575, w1=-0.08540209825257623
Gradient Descent(1/9): loss=0.7355399511210864, w0=0.0028260748191025545, w1=-0.10710503358376106
Gradient Descent(2/9): loss=0.8745310119270278, w0=-0.02317663771342304, w1=-0.1512618900052279
Gradient Descent(3/9): loss=0.7040519900404419, w0=0.014215452970795423, w1=-0.15265435776985858
Gradient Descent(4/9): loss=0.8244362513851042, w0=-0.009800138017542134, w1=-0.18133567400600156
Gradient Descent(5/9): loss=0.6881333466461039, w0=0.02122337686884569, w1=-0.17726360066954547
Gradient Descent(6/9): loss=0.7949914371339621, w0=-0.0005894677707352775, w1=-0.1990558594244548
Gradient Descent(7/9): loss=0.6782508390922272, w0=0.02547450870216095, w1=-0.1937267354716527
Gradient Descent(8/9): loss=0.7742230582298748, w0=0.006030002107113359, w1=-0.21145184153016922
Gradient Descent(9/9): loss=0.6720963177529482, w0=0.028166636510856866, w1=-0.20610228733558725


In [22]:



l,wnew=minimum_loss_vector(gd_losses, gd_ws)
l,wnew

(0.6720963177529482,
 array([ 0.00603   , -0.21145184,  0.00136542,  0.0514666 ,  0.0838281 ,
         0.02788115, -0.06819434,  0.06922147, -0.03850061,  0.07623958,
        -0.03203701,  0.13273401,  0.09374126,  0.19272094,  0.00991251,
        -0.05418337,  0.04050795,  0.01494053, -0.05908473,  0.01479213,
        -0.05794944, -0.01374753, -0.00398004,  0.04882016, -0.02988256,
        -0.05083417, -0.04283615,  0.00977123, -0.07276612,  0.08229117]))

In [23]:
y_pred=predict_labels(wnew, x_tr)

In [24]:
y_pred,y_tr

(array([-1., -1.,  1., ..., -1., -1.,  1.]),
 array([-1., -1.,  1., ..., -1., -1., -1.]))

In [25]:
accuracy_calculator(y_pred, y_tr)


0.737