In [1]:
import numpy as np
import math
import csv
from proj1_helpers import *
from Hadrien import *
from ML_methods import *
from features_engineering import *
import matplotlib.pyplot as plt


%load_ext autoreload
%autoreload 2

In [2]:
y, tx, ids = load_csv_data("data_csv/train.csv", sub_sample=True)

In [3]:
print("y has shape {0}".format(y.shape))
print("X has shape {0}".format(tx.shape))

y has shape (5000,)
X has shape (5000, 30)


#### NAN processing

In [4]:
## TODO : remove NAN before standardization, or at least not consider them in np.mean() and np.std.
tx_nan = transform_to_nan(tx, -900)
tx_nan_norm, mean_x, std_x = standardize_with_nan(tx_nan)

#met les nan a 0
tx_zero = transform_nan_to_zero(tx_nan)
#met les nan à la mean
tx_nan_mean, mean =transform_to_mean(tx_zero)

## Data split

In [15]:
def split_data(x, y, ratio, myseed=1):
    """split the dataset based on the split ratio."""
    # set seed
    np.random.seed(myseed)
    # generate random indices
    num_row = len(y)
    indices = np.random.permutation(num_row)
    index_split = int(np.floor(ratio * num_row))
    index_tr = indices[: index_split]
    index_te = indices[index_split:]
    # create split
    x_tr = x[index_tr]
    x_te = x[index_te]
    y_tr = y[index_tr]
    y_te = y[index_te]
    return x_tr, x_te, y_tr, y_te

## Basic Data

In [17]:
x_tr,x_te,y_tr,y_te=split_data(tx_nan_mean,y,0.8)

In [32]:
initial_w_gd = np.zeros(x_tr.shape[1])
max_iters = 1000
gamma = 0.000000000005
gd_losses, gd_ws = gradient_descent(y_tr, x_tr, initial_w_gd, max_iters, gamma)

Gradient Descent(0/999): loss=1.0, w0=-1.1902083750000023e-10, w1=-1.44043775e-10
Gradient Descent(1/999): loss=0.9999999632934747, w0=-2.38041607432555e-10, w1=-2.880875205350135e-10
Gradient Descent(2/999): loss=0.9999999265869669, w0=-3.5706230979771397e-10, w1=-4.3213123660506013e-10
Gradient Descent(3/999): loss=0.9999998898804765, w0=-4.760829445955266e-10, w1=-5.761749232101598e-10
Gradient Descent(4/999): loss=0.9999998531740033, w0=-5.951035118260423e-10, w1=-7.202185803503321e-10
Gradient Descent(5/999): loss=0.9999998164675475, w0=-7.141240114893105e-10, w1=-8.642622080255966e-10
Gradient Descent(6/999): loss=0.9999997797611093, w0=-8.331444435853803e-10, w1=-1.0083058062359727e-09
Gradient Descent(7/999): loss=0.9999997430546883, w0=-9.52164808114301e-10, w1=-1.1523493749814805e-09
Gradient Descent(8/999): loss=0.9999997063482848, w0=-1.0711851050761229e-09, w1=-1.2963929142621393e-09
Gradient Descent(9/999): loss=0.9999996696418987, w0=-1.1902053344708945e-09, w1=-1.440436

Gradient Descent(412/999): loss=0.9999848783829224, w0=-4.914985796017043e-08, w1=-5.948757248196005e-08
Gradient Descent(413/999): loss=0.9999848416835565, w0=-4.926885089651816e-08, w1=-5.96316040895927e-08
Gradient Descent(414/999): loss=0.999984804984208, w0=-4.938784376531885e-08, w1=-5.977563566776846e-08
Gradient Descent(415/999): loss=0.9999847682848768, w0=-4.950683656657254e-08, w1=-5.991966721648739e-08
Gradient Descent(416/999): loss=0.999984731585563, w0=-4.962582930027928e-08, w1=-6.006369873574947e-08
Gradient Descent(417/999): loss=0.9999846948862666, w0=-4.974482196643913e-08, w1=-6.020773022555475e-08
Gradient Descent(418/999): loss=0.9999846581869877, w0=-4.986381456505213e-08, w1=-6.035176168590324e-08
Gradient Descent(419/999): loss=0.999984621487726, w0=-4.998280709611833e-08, w1=-6.049579311679496e-08
Gradient Descent(420/999): loss=0.9999845847884817, w0=-5.010179955963778e-08, w1=-6.063982451822991e-08
Gradient Descent(421/999): loss=0.9999845480892547, w0=-5.0

Gradient Descent(840/999): loss=0.9999691726417945, w0=-1.0007266304382946e-07, w1=-1.2113040909377142e-07
Gradient Descent(841/999): loss=0.9999691359498638, w0=-1.0019162707455392e-07, w1=-1.2127442809565881e-07
Gradient Descent(842/999): loss=0.9999690992579503, w0=-1.0031059103775246e-07, w1=-1.2141844706809776e-07
Gradient Descent(843/999): loss=0.9999690625660544, w0=-1.0042955493342514e-07, w1=-1.2156246601108825e-07
Gradient Descent(844/999): loss=0.9999690258741757, w0=-1.00548518761572e-07, w1=-1.2170648492463032e-07
Gradient Descent(845/999): loss=0.9999689891823144, w0=-1.0066748252219311e-07, w1=-1.21850503808724e-07
Gradient Descent(846/999): loss=0.9999689524904704, w0=-1.007864462152885e-07, w1=-1.2199452266336927e-07
Gradient Descent(847/999): loss=0.9999689157986437, w0=-1.0090540984085823e-07, w1=-1.221385414885662e-07
Gradient Descent(848/999): loss=0.9999688791068345, w0=-1.0102437339890234e-07, w1=-1.222825602843148e-07
Gradient Descent(849/999): loss=0.9999688424

In [33]:
l,wnew=minimum_loss_vector(gd_losses, gd_ws)
l,wnew

(0.99996333884296,
 array([-1.18868142e-07, -1.43885046e-07, -1.40610021e-07, -3.29458968e-08,
         5.38061911e-10,  1.11326663e-07, -1.47107588e-09, -4.01904069e-09,
        -3.32593874e-08, -1.72480554e-07, -3.10697180e-09,  1.95029476e-09,
         1.28284072e-10, -4.01409494e-08,  9.89637715e-11, -9.77104229e-11,
        -7.91880225e-08,  1.80235396e-10, -1.03573010e-10, -6.74093554e-08,
        -3.02995041e-11, -2.60398938e-07, -8.75007457e-10, -3.10422650e-08,
        -1.46497008e-10, -1.30899020e-10, -9.16132290e-09,  4.33072386e-11,
        -1.05389527e-10, -5.31515697e-08, -1.09507134e-09, -4.65684605e-10,
         7.24950956e-11, -1.84771014e-10]))

In [34]:
y_pred=predict_labels(wnew, x_tr)

In [35]:
y_pred,y_tr

(array([-1., -1., -1., ..., -1., -1., -1.]),
 array([-1., -1.,  1., ..., -1., -1., -1.]))

In [36]:
accuracy_calculator(y_pred, y_tr)

0.674

## engineered feature 22

In [44]:
#test of feature engineering depending on classification by feature 22
tx_22plus = new_feature_PRI_jet_num(tx_nan_mean, 0.0)
tx_22plus = new_feature_PRI_jet_num(tx_22plus, 1.0)
tx_22plus = new_feature_PRI_jet_num(tx_22plus, 2.0)
tx_22plus = new_feature_PRI_jet_num(tx_22plus, 3.0)

print(np.shape(tx_22plus))

#split data
x_tr,x_te,y_tr,y_te=split_data(tx_22plus,y,0.8)
print(np.shape(x_tr))

#GD
initial_w_gd = np.zeros(tx_22plus.shape[1])
max_iters = 1000
gamma = 0.000000000005
gd_losses, gd_ws = gradient_descent(y_tr, x_tr, initial_w_gd, max_iters, gamma)

#losses
l,wnew=minimum_loss_vector(gd_losses, gd_ws)

#predictions
y_pred=predict_labels(wnew, x_tr)

#accuracy
accuracy_calculator(y_pred, y_tr)

(5000, 34)
(4000, 34)
Gradient Descent(0/999): loss=1.0, w0=-1.1902083750000023e-10, w1=-1.44043775e-10
Gradient Descent(1/999): loss=0.9999999632934747, w0=-2.38041607432555e-10, w1=-2.880875205350135e-10
Gradient Descent(2/999): loss=0.9999999265869669, w0=-3.5706230979771397e-10, w1=-4.3213123660506013e-10
Gradient Descent(3/999): loss=0.9999998898804765, w0=-4.760829445955266e-10, w1=-5.761749232101598e-10
Gradient Descent(4/999): loss=0.9999998531740033, w0=-5.951035118260423e-10, w1=-7.202185803503321e-10
Gradient Descent(5/999): loss=0.9999998164675475, w0=-7.141240114893105e-10, w1=-8.642622080255966e-10
Gradient Descent(6/999): loss=0.9999997797611093, w0=-8.331444435853803e-10, w1=-1.0083058062359727e-09
Gradient Descent(7/999): loss=0.9999997430546883, w0=-9.52164808114301e-10, w1=-1.1523493749814805e-09
Gradient Descent(8/999): loss=0.9999997063482848, w0=-1.0711851050761229e-09, w1=-1.2963929142621393e-09
Gradient Descent(9/999): loss=0.9999996696418987, w0=-1.190205334470

Gradient Descent(444/999): loss=0.9999837040118315, w0=-5.295759842020823e-08, w1=-6.409656931569436e-08
Gradient Descent(445/999): loss=0.9999836673130215, w0=-5.3076589195075e-08, w1=-6.42405999807169e-08
Gradient Descent(446/999): loss=0.999983630614229, w0=-5.319557990239631e-08, w1=-6.43846306162832e-08
Gradient Descent(447/999): loss=0.9999835939154539, w0=-5.33145705421722e-08, w1=-6.452866122239327e-08
Gradient Descent(448/999): loss=0.999983557216696, w0=-5.343356111440272e-08, w1=-6.467269179904714e-08
Gradient Descent(449/999): loss=0.9999835205179557, w0=-5.3552551619087926e-08, w1=-6.481672234624484e-08
Gradient Descent(450/999): loss=0.9999834838192325, w0=-5.3671542056227866e-08, w1=-6.496075286398636e-08
Gradient Descent(451/999): loss=0.9999834471205269, w0=-5.3790532425822585e-08, w1=-6.510478335227174e-08
Gradient Descent(452/999): loss=0.9999834104218386, w0=-5.390952272787214e-08, w1=-6.5248813811101e-08
Gradient Descent(453/999): loss=0.9999833737231677, w0=-5.402

Gradient Descent(834/999): loss=0.9999693927937442, w0=-9.935887744143576e-08, w1=-1.2026629446402821e-07
Gradient Descent(835/999): loss=0.9999693561017092, w0=-9.947784187731674e-08, w1=-1.2041031364260681e-07
Gradient Descent(836/999): loss=0.9999693194096916, w0=-9.95968062456715e-08, w1=-1.2055433279173683e-07
Gradient Descent(837/999): loss=0.9999692827176914, w0=-9.97157705465001e-08, w1=-1.2069835191141827e-07
Gradient Descent(838/999): loss=0.9999692460257082, w0=-9.98347347798026e-08, w1=-1.2084237100165117e-07
Gradient Descent(839/999): loss=0.9999692093337428, w0=-9.995369894557904e-08, w1=-1.2098639006243555e-07
Gradient Descent(840/999): loss=0.9999691726417945, w0=-1.0007266304382946e-07, w1=-1.2113040909377142e-07
Gradient Descent(841/999): loss=0.9999691359498638, w0=-1.0019162707455392e-07, w1=-1.2127442809565881e-07
Gradient Descent(842/999): loss=0.9999690992579503, w0=-1.0031059103775246e-07, w1=-1.2141844706809776e-07
Gradient Descent(843/999): loss=0.999969062566

0.674

## cos of features 17 and 14

In [43]:
features = [14, 17]
tx_cos = transform_feature_cos(tx_nan_mean, features)

#split data
x_tr,x_te,y_tr,y_te=split_data(tx_cos,y,0.8)

#GD
initial_w_gd = np.zeros(tx_cos.shape[1])
max_iters = 1000
gamma = 0.000000000005
gd_losses, gd_ws = gradient_descent(y_tr, x_tr, initial_w_gd, max_iters, gamma)

#losses
l,wnew=minimum_loss_vector(gd_losses, gd_ws)

#predictions
y_pred=predict_labels(wnew, x_tr)

#accuracy
accuracy_calculator(y_pred, y_tr)

Gradient Descent(0/999): loss=1.0, w0=-1.1902083750000023e-10, w1=-1.44043775e-10
Gradient Descent(1/999): loss=0.9999999632937169, w0=-2.3804160743267837e-10, w1=-2.880875205351076e-10
Gradient Descent(2/999): loss=0.9999999265874512, w0=-3.570623097980836e-10, w1=-4.3213123660534256e-10
Gradient Descent(3/999): loss=0.9999998898812028, w0=-4.760829445962658e-10, w1=-5.761749232107244e-10
Gradient Descent(4/999): loss=0.9999998531749718, w0=-5.951035118272741e-10, w1=-7.202185803512729e-10
Gradient Descent(5/999): loss=0.9999998164687582, w0=-7.14124011491158e-10, w1=-8.642622080270078e-10
Gradient Descent(6/999): loss=0.9999997797625619, w0=-8.331444435879667e-10, w1=-1.0083058062379484e-09
Gradient Descent(7/999): loss=0.9999997430563833, w0=-9.5216480811775e-10, w1=-1.1523493749841145e-09
Gradient Descent(8/999): loss=0.9999997063502218, w0=-1.0711851050805572e-09, w1=-1.296392914265526e-09
Gradient Descent(9/999): loss=0.9999996696440777, w0=-1.1902053344764372e-09, w1=-1.44043642

Gradient Descent(430/999): loss=0.9999842179011051, w0=-5.129172049118565e-08, w1=-6.208013692117839e-08
Gradient Descent(431/999): loss=0.9999841812022942, w0=-5.14107122117472e-08, w1=-6.22241679986309e-08
Gradient Descent(432/999): loss=0.9999841445035004, w0=-5.1529703864762723e-08, w1=-6.236819904662701e-08
Gradient Descent(433/999): loss=0.9999841078047241, w0=-5.1648695450232264e-08, w1=-6.25122300651667e-08
Gradient Descent(434/999): loss=0.9999840711059653, w0=-5.176768696815587e-08, w1=-6.265626105425002e-08
Gradient Descent(435/999): loss=0.9999840344072237, w0=-5.188667841853359e-08, w1=-6.280029201387697e-08
Gradient Descent(436/999): loss=0.9999839977084994, w0=-5.200566980136547e-08, w1=-6.294432294404758e-08
Gradient Descent(437/999): loss=0.9999839610097927, w0=-5.2124661116651564e-08, w1=-6.308835384476185e-08
Gradient Descent(438/999): loss=0.9999839243111033, w0=-5.224365236439192e-08, w1=-6.323238471601983e-08
Gradient Descent(439/999): loss=0.9999838876124312, w0=

Gradient Descent(834/999): loss=0.9999693929956633, w0=-9.935887748432334e-08, w1=-1.2026629449677872e-07
Gradient Descent(835/999): loss=0.9999693563038704, w0=-9.947784192030716e-08, w1=-1.2041031367543585e-07
Gradient Descent(836/999): loss=0.999969319612095, w0=-9.95968062887649e-08, w1=-1.2055433282464449e-07
Gradient Descent(837/999): loss=0.9999692829203368, w0=-9.97157705896966e-08, w1=-1.2069835194440467e-07
Gradient Descent(838/999): loss=0.999969246228596, w0=-9.98347348231023e-08, w1=-1.208423710347164e-07
Gradient Descent(839/999): loss=0.9999692095368724, w0=-9.995369898898208e-08, w1=-1.209863900955797e-07
Gradient Descent(840/999): loss=0.9999691728451664, w0=-1.0007266308733596e-07, w1=-1.211304091269946e-07
Gradient Descent(841/999): loss=0.9999691361534776, w0=-1.00191627118164e-07, w1=-1.212744281289611e-07
Gradient Descent(842/999): loss=0.9999690994618063, w0=-1.0031059108146627e-07, w1=-1.2141844710147925e-07
Gradient Descent(843/999): loss=0.9999690627701523, w0

0.674